// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	bookapi "github.com/ApacheThriftHelicopter/cloudwego-api-gateway/bookdemo/cmd/bookapi/hertz_router/bookapi"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	bookapi.Register(r)
}
