// Code generated by hertz generator.

package bookapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querybookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
