// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	book "github.com/ApacheThriftHelicopter/cloudwego-api-gateway/hertz-gateway/biz/router/book"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	book.Register(r)
}
