// Code generated by Kitex v0.6.1. DO NOT EDIT.
package booksvc

import (
	book "github.com/ApacheThriftHelicopter/cloudwego-api-gateway/kitex_gen/book"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler book.BookSvc, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
