// Code generated by hertz generator.

package book

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _insertbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querybookMw() []app.HandlerFunc {
	// your code...
	return nil
}
