// Code generated by hertz generator.

package book

import (
	"context"

	book "github.com/ApacheThriftHelicopter/cloudwego-api-gateway/biz/model/book"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryBook .
// @router book/query [GET]
func QueryBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req book.QueryBookReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(book.QueryBookResp)

	c.JSON(consts.StatusOK, resp)
}

// InsertBook .
// @router book/insert [POST]
func InsertBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req book.InsertBookReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(book.InsertBookResp)

	c.JSON(consts.StatusOK, resp)
}
