// Code generated by Kitex v0.6.0. DO NOT EDIT.

package bookservice

import (
	librarydemo "book/idl/kitex_gen/librarydemo"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return bookServiceServiceInfo
}

var bookServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "BookService"
	handlerType := (*librarydemo.BookService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateBook": kitex.NewMethodInfo(createBookHandler, newBookServiceCreateBookArgs, newBookServiceCreateBookResult, false),
		"MGetBook":   kitex.NewMethodInfo(mGetBookHandler, newBookServiceMGetBookArgs, newBookServiceMGetBookResult, false),
		"DeleteBook": kitex.NewMethodInfo(deleteBookHandler, newBookServiceDeleteBookArgs, newBookServiceDeleteBookResult, false),
		"QueryBook":  kitex.NewMethodInfo(queryBookHandler, newBookServiceQueryBookArgs, newBookServiceQueryBookResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "librarydemo",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.0",
		Extra:           extra,
	}
	return svcInfo
}

func createBookHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*librarydemo.BookServiceCreateBookArgs)
	realResult := result.(*librarydemo.BookServiceCreateBookResult)
	success, err := handler.(librarydemo.BookService).CreateBook(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBookServiceCreateBookArgs() interface{} {
	return librarydemo.NewBookServiceCreateBookArgs()
}

func newBookServiceCreateBookResult() interface{} {
	return librarydemo.NewBookServiceCreateBookResult()
}

func mGetBookHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*librarydemo.BookServiceMGetBookArgs)
	realResult := result.(*librarydemo.BookServiceMGetBookResult)
	success, err := handler.(librarydemo.BookService).MGetBook(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBookServiceMGetBookArgs() interface{} {
	return librarydemo.NewBookServiceMGetBookArgs()
}

func newBookServiceMGetBookResult() interface{} {
	return librarydemo.NewBookServiceMGetBookResult()
}

func deleteBookHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*librarydemo.BookServiceDeleteBookArgs)
	realResult := result.(*librarydemo.BookServiceDeleteBookResult)
	success, err := handler.(librarydemo.BookService).DeleteBook(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBookServiceDeleteBookArgs() interface{} {
	return librarydemo.NewBookServiceDeleteBookArgs()
}

func newBookServiceDeleteBookResult() interface{} {
	return librarydemo.NewBookServiceDeleteBookResult()
}

func queryBookHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*librarydemo.BookServiceQueryBookArgs)
	realResult := result.(*librarydemo.BookServiceQueryBookResult)
	success, err := handler.(librarydemo.BookService).QueryBook(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBookServiceQueryBookArgs() interface{} {
	return librarydemo.NewBookServiceQueryBookArgs()
}

func newBookServiceQueryBookResult() interface{} {
	return librarydemo.NewBookServiceQueryBookResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateBook(ctx context.Context, req *librarydemo.CreateBookRequest) (r *librarydemo.CreateBookResponse, err error) {
	var _args librarydemo.BookServiceCreateBookArgs
	_args.Req = req
	var _result librarydemo.BookServiceCreateBookResult
	if err = p.c.Call(ctx, "CreateBook", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetBook(ctx context.Context, req *librarydemo.MGetBookRequest) (r *librarydemo.MGetBookResponse, err error) {
	var _args librarydemo.BookServiceMGetBookArgs
	_args.Req = req
	var _result librarydemo.BookServiceMGetBookResult
	if err = p.c.Call(ctx, "MGetBook", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteBook(ctx context.Context, req *librarydemo.DeleteNoteRequest) (r *librarydemo.DeleteBookResponse, err error) {
	var _args librarydemo.BookServiceDeleteBookArgs
	_args.Req = req
	var _result librarydemo.BookServiceDeleteBookResult
	if err = p.c.Call(ctx, "DeleteBook", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryBook(ctx context.Context, req *librarydemo.QueryBookRequest) (r *librarydemo.QueryBookResponse, err error) {
	var _args librarydemo.BookServiceQueryBookArgs
	_args.Req = req
	var _result librarydemo.BookServiceQueryBookResult
	if err = p.c.Call(ctx, "QueryBook", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
