// Code generated by Kitex v0.6.0. DO NOT EDIT.

package bookservice

import (
	librarydemo "book/idl/kitex_gen/librarydemo"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateBook(ctx context.Context, req *librarydemo.CreateBookRequest, callOptions ...callopt.Option) (r *librarydemo.CreateBookResponse, err error)
	MGetBook(ctx context.Context, req *librarydemo.MGetBookRequest, callOptions ...callopt.Option) (r *librarydemo.MGetBookResponse, err error)
	DeleteBook(ctx context.Context, req *librarydemo.DeleteNoteRequest, callOptions ...callopt.Option) (r *librarydemo.DeleteBookResponse, err error)
	QueryBook(ctx context.Context, req *librarydemo.QueryBookRequest, callOptions ...callopt.Option) (r *librarydemo.QueryBookResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kBookServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBookServiceClient struct {
	*kClient
}

func (p *kBookServiceClient) CreateBook(ctx context.Context, req *librarydemo.CreateBookRequest, callOptions ...callopt.Option) (r *librarydemo.CreateBookResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateBook(ctx, req)
}

func (p *kBookServiceClient) MGetBook(ctx context.Context, req *librarydemo.MGetBookRequest, callOptions ...callopt.Option) (r *librarydemo.MGetBookResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetBook(ctx, req)
}

func (p *kBookServiceClient) DeleteBook(ctx context.Context, req *librarydemo.DeleteNoteRequest, callOptions ...callopt.Option) (r *librarydemo.DeleteBookResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteBook(ctx, req)
}

func (p *kBookServiceClient) QueryBook(ctx context.Context, req *librarydemo.QueryBookRequest, callOptions ...callopt.Option) (r *librarydemo.QueryBookResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryBook(ctx, req)
}
