// Code generated by Kitex v0.6.0. DO NOT EDIT.
package bookservice

import (
	librarydemo "book/idl/kitex_gen/librarydemo"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler librarydemo.BookService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
